// Inlines the Lucide icons the video uses into src/icons.gen.js (ISC license, lucide.dev).
import fs from 'node:fs';
const names = ['user-check', 'messages-square', 'clipboard-check', 'calendar-days', 'users', 'flag', 'target',
  'mountain', 'megaphone', 'search', 'sprout', 'trending-up', 'circle-alert', 'message-circle-question',
  'lightbulb', 'hand-helping', 'message-circle', 'rocket', 'check', 'hand', 'handshake', 'calendar-range',
  'message-square-quote', 'message-circle-more', 'eye', 'repeat', 'route', 'goal', 'mountain-snow', 'arrow-right',
  'mouse-pointer-2', 'file-text', 'network', 'arrow-down-right', 'waves', 'chart-no-axes-combined', 'hand-heart'];
const out = {};
for (const n of names) {
  const svg = fs.readFileSync(`node_modules/lucide-static/icons/${n}.svg`, 'utf8');
  out[n] = svg.replace(/<!--.*?-->/gs, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '');
}
fs.writeFileSync('src/icons.gen.js', '// Generated by tools/build-icons.mjs from lucide-static (ISC). Do not edit.\nwindow.LUCIDE = ' + JSON.stringify(out, null, 1) + ';\n');
console.log('icons:', Object.keys(out).length);
